apiVersion: v1
kind: Service
metadata:
  name: python-visitor-counter-svc
spec:
  selector:
    app: python-visitor-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
